config/routes.rb
Rails.application.routes.draw do
  resources :locations
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :teachers do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:destroy, :show]

  get "/dashboard/myclasses", to: "dashboards#myclasses", as: :dashboard
  get "/dashboard/myreservations", to: "dashboards#myreservations"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :teacher
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo

  def first_name
    user.first_name
  end

  def last_name
    user.last_name
  end

  def city
    user.city
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :teachers
  has_many :bookings
  has_many :myclasses, through: :teachers, source: :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit::Authorization

  # Pundit: white-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_teacher, only: [:new, :create]

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.teacher = Teacher.find(params[:teacher_id])
    @booking.user = current_user
    flash[:notice] = @booking.errors.full_messages.to_sentence unless @booking.save
    authorize @booking
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:date)
  end

  def set_teacher
    @teacher = Teacher.find(params[:teacher_id])
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  skip_after_action :verify_authorized, only: %i[myclasses myreservations]

  def myclasses
    @user = current_user
    @myclasses = @user.myclasses
    #authorize @teacher
  end

  def myreservations
    @user = current_user
    @bookings = @user.bookings
    # authorize @teacher
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[ show edit update destroy ]

  # GET /locations or /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1 or /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations or /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to location_url(@location), notice: "Location was successfully created." }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to location_url(@location), notice: "Location was successfully updated." }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url, notice: "Location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:address, :city)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
    @user = User.first
    @teachers = Teacher.all
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @teachers = policy_scope(Teacher)
    @user = current_user
  end

  def new
    @teacher = Teacher.new
    authorize @teacher
  end

  def edit
    @teacher = Teacher.find(params[:id])
    authorize @teacher
  end

  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.user = current_user
    @teacher.save
    authorize @teacher
    if @teacher.save
      redirect_to teacher_path(@teacher)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @teacher = Teacher.find(params[:id])
    authorize @teacher
  end

  private

  def teacher_params
    params.require(:teacher).permit(:price, :photo, :feature, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="newformT" style="background-image: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)), url('https://cdn.pixabay.com/photo/2014/11/22/18/38/wine-541922_960_720.jpg')">

  <div class="card-container" >
    <div class="card-my-booking u-clearfix">
      <div class="card-body">
        <span class="card-number card-circle subtle">W</span>
        <span class="card-author subtle"><%=@teacher.user.first_name.capitalize%> <%=@teacher.user.last_name.capitalize%> - <%= @teacher.user.city %></span>
        <h2 class="card-title">Book now!</h2>
        <span class="card-description subtle">
        </span>
        <div class="card-read">
          <span class="card-author subtle"><%= @teacher.feature%></span>
          <p>Half day session rate: <%= @teacher.price.to_i%>$</p>
          <%= simple_form_for([@teacher, @booking]) do |f| %>
          <span class="card-author subtle"><%= f.input :date, as: :date, label: "Date #{@teacher.user.first_name}", html5: true %></span>
          <%= f.submit "Book", class: 'btn button-main' %>
          <% end %>
          <%= link_to "Back to œnologists", teachers_path %>
        </div>
        <span class="card-tag card-circle subtle">W</span>
      </div>
      <% if @teacher.photo.attached? %>
          <%= cl_image_tag @teacher.photo.key, class: "card-media" %>
        <% else %>
          <img src="https://images.unsplash.com/photo-1566995541428-f2246c17cda1?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1064" alt="" class="card-media" />
      <% end %>
    </div>
    <div class="card-shadow"></div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/bookings/show.html.erb
<% require "date"%>

<br>
<br>
<br>
<br>
<div class="card-container">
  <div class="card-my-booking u-clearfix">
    <div class="card-body">
      <span class="card-number card-circle subtle">B</span>
      <span class="card-author subtle"><%=@booking.teacher.user.first_name%> <%=@booking.teacher.user.last_name%></span>
      <h2 class="card-title"><%=@booking.date.strftime(' %m %b %Y')%></h2>
      <span class="card-description subtle">Club Oenologique, a celebration of the authentic, the artisan and the analogue, is a sumptuous quarterly magazine about wine, spirits and good living: the profound depth of a fine wine.</span>
      <div class="card-read"><%= link_to dashboard_path do %>Book<% end %></div>
      <span class="card-tag card-circle subtle">B</span>
    </div>
    <img src="https://images.unsplash.com/photo-1566995541428-f2246c17cda1?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1064" alt="" class="card-media" />
  </div>
  <div class="card-shadow"></div>
</div>
<%= render 'shared/footer' %>

app/views/dashboards/myclasses.html.erb
<div class="card-profile">
    <img src="https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070" />
    <div class="card-profile-infos">
      <div>
      <br>
        <h2><%= current_user.first_name %> <%= current_user.last_name %></h2>
        <h2><%= current_user.city %></h2>
      <br>
        <p>Une séance d'œnologie est à la fois une exploration des sens et du savoir.<br>
        En effet, c'est d'abord une méthode de dégustation en 3 étapes qui font appel à vos sens :<br>
        - observer le vin,<br>
        - sentir le vin,<br>
        - le mettre en bouche.<br>
        Déguster un vin est aussi un voyage à travers l'histoire d'un terroir, sa géologie, la technicité de l'homme, la géographie...<br>
        Un atelier ou une séance d'œnologie est l'ensemble de tous ces éléments qui combinent les sens et l'intellect. </p>
        <%#= current_user.feature %>
        <br>
      <img src="https://images.unsplash.com/photo-1438761681033-6461ffad8d80?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070" class="card-profile-user avatar-bordered" />
      </div>
    </div>
</div>
<br>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" aria-current="page">MY CLASSES</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="myreservations">MY RESERVATIONS</a>
  </li>
</ul>

<div class="cards">
  <% @myclasses.each do |cours| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1541971897566-308cf7ad0934?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070)">
    <%=cours.date.strftime('%m %b %Y')%>
    </div>
  <% end %>
</div>

<%#

    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1598306442890-742e834da092?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1674)">
      Sat May 28th, 2022
    </div>

    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1596438214057-5ff7c7fa76b1?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070)">
      Thu Jun 2nd, 2022
    </div>

    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1652466439798-fe090b23f18e?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2832)">
      Fri Jun 3rd, 2022
    </div>

    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1513618827672-0d7c5ad591b1?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070)">
      Sat Jun 5th, 2022
    </div>

    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1519671282429-b44660ead0a7?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070)">
      Sun Jun 6th, 2022
    </div> %>

app/views/dashboards/myreservations.html.erb
<div class="card-profile">
    <img src="https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070" />
    <div class="card-profile-infos">
      <div>
      <br>
        <h2><%= current_user.first_name %> <%= current_user.last_name %></h2>
        <h2><%= current_user.city %></h2>
      <br>
        <p>Une séance d'œnologie est à la fois une exploration des sens et du savoir.<br>
        En effet, c'est d'abord une méthode de dégustation en 3 étapes qui font appel à vos sens :<br>
        - observer le vin,<br>
        - sentir le vin,<br>
        - le mettre en bouche.<br>
        Déguster un vin est aussi un voyage à travers l'histoire d'un terroir, sa géologie, la technicité de l'homme, la géographie...<br>
        Un atelier ou une séance d'œnologie est l'ensemble de tous ces éléments qui combinent les sens et l'intellect. </p>
        <%#= current_user.feature %>
        <br>
      <img src="https://images.unsplash.com/photo-1438761681033-6461ffad8d80?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070" class="card-profile-user avatar-bordered" />
      </div>
    </div>
</div>
<br>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" href="myclasses">MY CLASSES</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" aria-current="page">MY RESERVATIONS</a>
  </li>
</ul>

<div class="cards">
  <% @bookings.each do |cours| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1541971897566-308cf7ad0934?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070)">
    <%=cours.date.strftime('%m %b %Y')%>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WINEBnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render 'shared/navbar' %>

    <div class="main-container">
        <%= yield %>
    </div>

  </body>
</html>

app/views/locations/_form.html.erb
<%= simple_form_for(@location) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :address %>
    <%= f.input :city %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<div id="<%= dom_id location %>">
  <p>
    <strong>Address:</strong>
    <%= location.address %>
  </p>

  <p>
    <strong>City:</strong>
    <%= location.city %>
  </p>

</div>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render "form", location: @location %>

<br>

<div>
  <%= link_to "Show this location", @location %> |
  <%= link_to "Back to locations", locations_path %>
</div>

app/views/locations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Locations</h1>

<div id="locations">
  <% @locations.each do |location| %>
    <%= render location %>
    <p>
      <%= link_to "Show this location", location %>
    </p>
  <% end %>
</div>

<%= link_to "New location", new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render "form", location: @location %>

<br>

<div>
  <%= link_to "Back to locations", locations_path %>
</div>

app/views/locations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @location %>

<div>
  <%= link_to "Edit this location", edit_location_path(@location) %> |
  <%= link_to "Back to locations", locations_path %>

  <%= button_to "Destroy this location", @location, method: :delete %>
</div>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>
<%= render 'shared/card' %>

app/views/shared/_banner.html.erb
<div class="wrapper">
  <video id="background-video" autoplay loop muted src="https://ak.picdn.net/shutterstock/videos/1069994935/preview/stock-footage-joyful-couple-having-a-romantic-dinner-at-a-fancy-restaurant-people-enjoying-their-date-drinking.webm" type="video/mp4" style="background-color: none !important">
  </video>
  <div data-controller="typed-strings">
    <h1>Welcome to <span data-controller="typed"></span></h1>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="container-home">
  <ul class="cards-home">
    <% @teachers.last(3).each do |t| %>
      <li>
        <%= link_to teacher_path(t), class: 'card-home' do %>
          <% if t.photo.attached? %>
            <%= cl_image_tag t.photo.key, class: "card__image" %>
          <% end %>
          <div class="card__overlay">
            <div class="card__header">
              <svg class="card__arc" xmlns="http://www.w3.org/2000/svg"><path /></svg>
              <img class="card__thumb" src="https://i.imgur.com/7D7I6dI.png" alt="" />
              <div class="card__header-text">
                <h3 class="card__title"><%= t.user.first_name.capitalize %> <%= t.user.last_name.capitalize %></h3>
              </div>
            </div>
            <p class="card__description">
              <%= t.feature %>
            </p>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
  <%= link_to 'Discover all our oenologists', teachers_path, class: 'btn button-main', style: 'text-decoration: none; color: black; font-size: 20px'  %>
</div>

app/views/shared/_navbar.html.erb
<div class="nav-custom">

  <input type="checkbox" id="burger-toggle">

  <label for="burger-toggle" class="burger-menu">
    <div class="line"></div>
    <div class="line"></div>
    <div class="line"></div>
  </label>

  <div class="menu">
    <div class="menu-inner">
      <ul class="menu-nav">
        <% if user_signed_in? %>

          <li class="menu-nav-item"><%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "menu-nav-link" %>
          </li>
        <% else %>
          <li class="menu-nav-item"><%= link_to "Login", new_user_session_path, class: "menu-nav-link" %>
          </li>
        <% end %>
      </ul>

      <div class="gallery">
        <div class="title">
          <p>WineBnB gallery</p>
        </div>
        <div class="images">
          <%= link_to root_path, class: 'image-link' do %>
            <div class="image" data-label="Home">
              <img src="https://cdn.pixabay.com/photo/2014/11/22/18/38/wine-541922_960_720.jpg" alt="">
            </div>
          <% end %>
          <%= link_to teachers_path, class: 'image-link' do %>
            <div class="image" data-label="Our oenologists">
              <img src="https://cdn.pixabay.com/photo/2016/03/27/18/53/drinks-1283608__340.jpg" alt="">
            </div>
          <% end %>
          <%= link_to new_teacher_path, class: 'image-link' do %>
            <div class="image" data-label="Become Oenologist">
              <img src="https://cdn.pixabay.com/photo/2016/09/10/13/34/grapes-1659118__340.jpg" alt="">
            </div>
          <% end %>
          <%= link_to dashboard_path, class: 'image-link' do %>
            <div class="image" data-label="Booking dashboard">
              <img src="https://cdn.pixabay.com/photo/2012/07/26/20/55/barrels-52934__340.jpg" alt="">
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/teachers/new.html.erb
<div class="formnewT" style="background-image: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)), url('https://cdn.pixabay.com/photo/2014/11/22/18/38/wine-541922_960_720.jpg')">
  <div class="card-container" >
    <div class="card-my-booking u-clearfix">
      <div class="card-body">
        <span class="card-number card-circle subtle">W</span>

        <h2 class="card-title">Welcome to WineBnB</h2>
        <span class="card-description subtle">Create your oenologist profile in 2 minutes and share your passion</span>
        <div class="card-read">
          <%= simple_form_for @teacher do |f| %>
            <%= f.input :photo, label: 'Add your picture', as: :file %>
            <%= f.input :feature, label: 'Main skills', placeholder: 'Wines of Bordeaux' %>
            <%= f.input :price, label: "Rate per half day" %>
            <%= f.submit "Register", class: 'btn button-main'%>
          <% end %>
          <%= link_to "Back to oenologists", teachers_path %>
        </div>
        <span class="card-tag card-circle subtle">W</span>
      </div>
      <img src="https://images.unsplash.com/photo-1566995541428-f2246c17cda1?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1064" alt="" class="card-media" />
    </div>
    <div class="card-shadow"></div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/teachers/show.html.erb
<% require "date"%>

<br>
<br>
<br>
<br>
<div class="formnewT" style="background-image: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)), url('https://cdn.pixabay.com/photo/2014/11/22/18/38/wine-541922_960_720.jpg')">
  <div class="card-container">
    <div class="card-my-booking u-clearfix">
      <div class="card-body">
        <span class="card-number card-circle subtle">B</span>
        <span class="card-author subtle"><p><%=@teacher.user.city%></p></span>
          <h2 class="card-title"><%=@teacher.user.first_name.capitalize%> <%=@teacher.user.last_name.capitalize%></h2>
        <span class="card-description subtle"><p><%=@teacher.feature%></p></span>
        <div class="card-price my-2"><%=@teacher.price.to_i%> €</div>
        <%= link_to "Book Now!", new_teacher_booking_path(@teacher.id), class: "button-main my-4"%>

        <div class="social-logo">
                <a id ="teacher" href="#"><i class="fa fa-dribbble"></i></a><br>
                <a id ="teacher" href="#"><i class="fa fa-twitter"></i></a><br>
                <a id ="teacher" href="#"><i class="fa fa-linkedin"></i></a><br>
                <a id ="teacher" href="#"><i class="fa fa-facebook"></i></a><br>
              </div>
      </div>
        <%=cl_image_tag @teacher.photo.key, class:"card-media" %>
    </div>

  </div>
</div>
  <%= render 'shared/footer' %>